Logging to shared log directory: /tmp/test_logs//1333467793
only running test 20
excepting tests: 15c
Starting client mft02: -o user_xattr,acl,flock mft02@tcp:/lustre /mnt/lustre2
Started clients mft02: 
mft02@tcp:/lustre on /mnt/lustre2 type lustre (rw,user_xattr,acl,flock)
debug=-1
subsystem_debug=0xffb7e3ff
debug_mb=2
mft02: Checking config lustre mounted on /mnt/lustre
Checking servers environments
Checking clients mft02 environments
Using TIMEOUT=20
disable quota as required
debug=-1
subsystem_debug=0xffb7e3ff
debug_mb=2
setting all flavor to null
already have total 8 null connections
.....................

== replay-dual test 20: recovery time is not increasing == 18:43:24 (1333467804)
Filesystem           1K-blocks      Used Available Use% Mounted on
mft02@tcp:/lustre       374928     49528    305272  14% /mnt/lustre
Failing mds1 on node mft02
Stopping /mnt/mds1 (opts:) on mft02
affected facets: mds1
Failover mds1 to mft02
18:43:38 (1333467818) waiting for mft02 network 900 secs ...
18:43:38 (1333467818) network interface is UP
Starting mds1: -o loop,user_xattr,acl  /tmp/lustre-mdt1 /mnt/mds1
debug=-1
subsystem_debug=0xffb7e3ff
debug_mb=2
Started lustre-MDT0000
Starting client: mft02: -o user_xattr,acl,flock mft02@tcp:/lustre /mnt/lustre2
debug=-1
subsystem_debug=0xffb7e3ff
debug_mb=2
Filesystem           1K-blocks      Used Available Use% Mounted on
mft02@tcp:/lustre       374928     49528    305272  14% /mnt/lustre
Failing mds1 on node mft02
Stopping /mnt/mds1 (opts:) on mft02
affected facets: mds1
Failover mds1 to mft02
18:46:13 (1333467973) waiting for mft02 network 900 secs ...
18:46:13 (1333467973) network interface is UP
Starting mds1: -o loop,user_xattr,acl  /tmp/lustre-mdt1 /mnt/mds1
debug=-1
subsystem_debug=0xffb7e3ff
debug_mb=2
Started lustre-MDT0000
Starting client: mft02: -o user_xattr,acl,flock mft02@tcp:/lustre /mnt/lustre2
debug=-1
subsystem_debug=0xffb7e3ff
debug_mb=2
Resetting fail_loc on all nodes...done.
